---
- name: Install python 2
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Create the user 'rke'
  user:
    name: rke
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Set authorized keys taken from url
  authorized_key:
    user: rke
    state: present
    key: "{{ item }}"
  with_items: "{{ user_keys }}"
  when: user_keys