---

- name: etcd nodes - Inbound rules
  iptables:
    chain: INPUT
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.dest_port }}"
    jump: ACCEPT
    comment: etcd nodes - Inbound rules
  with_items:
    - {dest_port: 2376 , protocol: tcp}
    - {dest_port: 2379 , protocol: tcp}
    - {dest_port: 2380 , protocol: tcp}
    - {dest_port: 9099 , protocol: tcp}
    - {dest_port: 10250, protocol: tcp}
    - {dest_port: 8472 , protocol: udp}
  when: "'etcd' in group_names"

- name: etcd nodes - Outbound rules
  iptables:
    chain: OUTPUT
    protocol: "{{ item.protocol }}"
    source_port: "{{ item.src_port }}"
    jump: ACCEPT
    comment: etcd nodes - Outbound rules
  with_items:
    - {src_port: 443  , protocol: tcp}
    - {src_port: 2379 , protocol: tcp}
    - {src_port: 2380 , protocol: tcp}
    - {src_port: 6443 , protocol: tcp}
    - {src_port: 9099 , protocol: tcp}
    - {src_port: 8472 , protocol: udp}
  when: "'etcd' in group_names"

- name: controlplane nodes - Inbound rules
  iptables:
    chain: INPUT
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.dest_port }}"
    jump: ACCEPT
    comment: controlplane nodes - Inbound rules
  with_items:
    - {dest_port: 80            , protocol: tcp}
    - {dest_port: 443           , protocol: tcp}
    - {dest_port: 2376          , protocol: tcp}
    - {dest_port: 6443          , protocol: tcp}
    - {dest_port: 9099          , protocol: tcp}
    - {dest_port: 10250         , protocol: tcp}
    - {dest_port: 10254         , protocol: tcp}
    - {dest_port: "30000:32767" , protocol: tcp}
    - {dest_port: "30000:32767" , protocol: udp}
    - {dest_port: 8472          , protocol: udp}
  when: "'controlplane' in group_names"

- name: controlplane nodes - Outbound rules
  iptables:
    chain: OUTPUT
    protocol: "{{ item.protocol }}"
    source_port: "{{ item.src_port }}"
    jump: ACCEPT
    comment: controlplane nodes - Outbound rules
  with_items:
    - {src_port: 443   , protocol: tcp}
    - {src_port: 2379  , protocol: tcp}
    - {src_port: 2380  , protocol: tcp}
    - {src_port: 9099  , protocol: tcp}
    - {src_port: 10250 , protocol: tcp}
    - {src_port: 10254 , protocol: tcp}
    - {src_port: 8472  , protocol: udp}
  when: "'controlplane' in group_names"


- name: worker nodes - Inbound rules
  iptables:
    chain: INPUT
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.dest_port }}"
    jump: ACCEPT
    comment: worker nodes - Inbound rules
  with_items:
    - {dest_port: 80            , protocol: tcp}
    - {dest_port: 443           , protocol: tcp}
    - {dest_port: 2376          , protocol: tcp}
    - {dest_port: 9099          , protocol: tcp}
    - {dest_port: 10250         , protocol: tcp}
    - {dest_port: 10254         , protocol: tcp}
    - {dest_port: "30000:32767" , protocol: tcp}
    - {dest_port: "30000:32767" , protocol: udp}
    - {dest_port: 8472          , protocol: udp}
  when: "'worker' in group_names"

- name: worker nodes - Outbound rules
  iptables:
    chain: OUTPUT
    protocol: "{{ item.protocol }}"
    source_port: "{{ item.src_port }}"
    jump: ACCEPT
    comment: worker nodes - Outbound rules
  with_items:
    - {src_port: 443  , protocol: tcp}
    - {src_port: 6443 , protocol: tcp}
    - {src_port: 9099 , protocol: tcp}
    - {src_port: 10254, protocol: tcp}
    - {src_port: 8472 , protocol: udp}
  when: "'worker' in group_names"

- name: RKE nodes - Outbound rules
  iptables:
    chain: OUTPUT
    protocol: "{{ item.protocol }}"
    source_port: "{{ item.src_port }}"
    jump: ACCEPT
    comment: RKE nodes - Outbound rules
  with_items:
    - {src_port: 22   , protocol: tcp}
    - {src_port: 6443 , protocol: tcp}
  when: "'master' in group_names"