---

docker__edition: "ce"
docker__channel: ["stable"]
docker__version: "18.06.2"
docker__state: "present"

docker__users: ["{{ ansible_env.SUDO_USER | d('root') }}"]

docker__registries: []

docker__default_daemon_json: |
  "log-driver": "journald",
  "fixed-cidr": "192.168.1.1/24"
docker__daemon_json: ""

docker__daemon_flags:
  - "-H unix://"

docker__daemon_environment: []

docker__systemd_override: ""

docker__cron_jobs_prune_flags: "af"
docker__cron_jobs:
  - name: "Docker disk clean up"
    job: "docker system prune -{{ docker__cron_jobs_prune_flags }} > /dev/null 2>&1"
    schedule: ["0", "0", "*", "*", "0"]
    cron_file: "docker-disk-clean-up"
    user: "{{ (docker__users | first) | d('root') }}"

docker__package_dependencies:
  - "apt-transport-https"
  - "ca-certificates"
  - "cron"
  - "gnupg2"
  - "software-properties-common"

docker__apt_key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
docker__apt_key_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker__apt_repository: >
  deb [arch=amd64]
  https://download.docker.com/linux/{{ ansible_distribution | lower }}
  {{ ansible_distribution_release }} {{ docker__channel | join (' ') }}